remote_theme: vanjac/theme
defaults:
  -
    scope:
      path: ""
    values:
      links:
        -
          title: Download
          url: https://github.com/vanjac/chromafiler/releases
        -
          title: Wiki
          url: https://github.com/vanjac/chromafiler/wiki
        -
          title: GitHub
          url: https://github.com/vanjac/chromafiler
